// Generated by `sieve export-types` from sieve/contracts.py.
// Do not edit: run `sieve export-types` and commit the result.

// --- unions -------------------------------------------------------------

export type Modality = "llm" | "text-to-image" | "image-editing" | "text-to-video" | "image-to-video" | "text-to-speech" | "speech-to-text" | "music";

export type Unit = "index_0_100" | "fraction" | "elo" | "usd_per_1m_tokens" | "tokens_per_s" | "seconds" | "usd_per_image" | "usd_per_second" | "usd_per_1m_chars" | "count";

export type Transform = "identity" | "neg_log" | "log" | "invert";

export type DecisionKind = "switch" | "hold" | "suspend" | "weights" | "policy" | "apply" | "pull";

export type Scope = "read" | "profiles:write" | "apply" | "telemetry";


// --- models -------------------------------------------------------------

export interface Axis {
  name: string;
  modality: Modality;
  label: string;
  describes: string;
  fields: AxisField[];
  missing?: "renormalise" | "penalise";
  min_coverage?: number;
  higher_is_better?: boolean;
}


export interface AxisField {
  source: string;
  field: string;
  weight?: number;
  transform?: Transform;
  min_n?: number | null;
  phase?: number;
}


export interface AxisScore {
  axis: string;
  value: number | null;
  coverage: number;
  contribution: number;
}


/** What a model can do. From inventory and OpenRouter; never from a benchmark. */
export interface Capability {
  tools?: boolean | null;
  reasoning?: boolean | null;
  structured_output?: boolean | null;
  context_window?: number | null;
  max_output?: number | null;
  input_modalities?: string[];
  output_modalities?: string[];
}


export interface Chain {
  profile: string;
  computed_at: string;
  primary: string;
  fallbacks?: string[];
  local?: Record<string, string[]>;
  incumbent?: string | null;
  incumbent_since?: string | null;
}


export interface Decision {
  id: string;
  at: string;
  profile: string;
  kind: DecisionKind;
  actor: string;
  before?: unknown | null;
  after?: unknown | null;
  reason: string;
  detail?: Record<string, unknown>;
}


/** What one engine run produced. */
export interface EngineResult {
  snapshot: string;
  at: string;
  rankings?: Ranking[];
  chains?: Chain[];
  decisions?: Decision[];
  targets?: TargetResult[];
  warnings?: string[];
  dry_run?: boolean;
}


export interface InventoryConfig {
  name: string;
  kind: string;
  base_url?: string | null;
  token_env?: string | null;
  models?: string[];
  options?: Record<string, unknown>;
}


/** One model, in one modality, under its canonical id. */
export interface ModelRef {
  id: string;
  modality: Modality;
  name: string;
  creator: string;
  aliases?: string[];
  release_date?: string | null;
}


/** One measured value. Append-only; nothing is ever overwritten. */
export interface Observation {
  model_id: string;
  modality: Modality;
  source: string;
  field: string;
  value: number;
  unit: Unit;
  n?: number | null;
  ci95?: number | null;
  observed_at: string;
  pulled_at: string;
}


export interface Policy {
  margin?: number;
  max_tenure_days?: number;
  min_confidence?: number;
  chain?: number;
  suspend_below_health?: number;
  auto_apply?: boolean;
  require_telemetry?: boolean;
}


export interface Price {
  model_id: string;
  source: string;
  unit: Unit;
  input?: number | null;
  output?: number | null;
  cached_input?: number | null;
  per_unit?: number | null;
  source_url?: string | null;
  observed_at: string;
}


export interface Profile {
  name: string;
  modality: Modality;
  purpose: string;
  weights: Record<string, number>;
  require?: Record<string, unknown>;
  shape?: Shape;
  policy?: Policy;
  targets?: string[];
}


export interface PullResult {
  source: string;
  models?: ModelRef[];
  observations?: Observation[];
  prices?: Price[];
  rate_limit?: RateLimit;
  warnings?: string[];
}


export interface Rank {
  position: number;
  model_id: string;
  reachable: boolean;
  local_ids?: string[];
  score: number;
  confidence: number;
  health: number;
  final: number;
  axes?: AxisScore[];
  cost_per_task?: number | null;
  dominated_by?: string | null;
  excluded_by?: string | null;
  flip?: string | null;
}


export interface Ranking {
  profile: string;
  modality: Modality;
  computed_at: string;
  snapshot: string;
  ranks?: Rank[];
}


export interface RateLimit {
  limit?: number | null;
  remaining?: number | null;
  reset_at?: string | null;
}


/** A model the user can actually reach, and where. */
export interface Reachable {
  inventory: string;
  local_id: string;
  model_id?: string | null;
  capability?: Capability;
  seen_at: string;
}


/** Per profile; only the keys the modality uses. The YAML spells the token fields `in` and `out` (PLAN section 4); both are accepted, and the JSON name stays `i... */
export interface Shape {
  in_tokens?: number | null;
  out_tokens?: number | null;
  cached?: number | null;
  images?: number | null;
  seconds?: number | null;
  chars?: number | null;
}


/** One `[sources.<name>]` block of sieve.toml, resolved. */
export interface SourceConfig {
  name: string;
  enabled?: boolean;
  key_env?: string | null;
  modalities?: Modality[];
  dir?: string | null;
  options?: Record<string, unknown>;
}


export interface TargetConfig {
  name: string;
  kind: string;
  dir?: string | null;
  url?: string | null;
  options?: Record<string, unknown>;
}


export interface TargetResult {
  target: string;
  written?: string[];
  dry_run?: boolean;
  detail?: Record<string, unknown>;
  error?: string | null;
}


export interface TelemetryEvent {
  model: string;
  profile?: string | null;
  ok: boolean;
  status?: number | null;
  latency_ms?: number | null;
  tokens_in?: number | null;
  tokens_out?: number | null;
  at: string;
}
