// Generated by `sieve export-types` from sieve/contracts.py.
// Do not edit: run `sieve export-types` and commit the result.

// --- unions -------------------------------------------------------------

export type Modality = "llm" | "text-to-image" | "image-editing" | "text-to-video" | "image-to-video" | "video-editing" | "text-to-speech" | "speech-to-text" | "speech-to-speech" | "music";

export type Unit = "index_0_100" | "fraction" | "elo" | "usd_per_1m_tokens" | "tokens_per_s" | "seconds" | "usd_per_image" | "usd_per_second" | "usd_per_compute_second" | "usd_per_1m_chars" | "usd_per_megapixel" | "usd_per_request" | "count" | "usd_per_task";

export type Transform = "identity" | "neg_log" | "log" | "invert";

export type DecisionKind = "switch" | "hold" | "suspend" | "weights" | "policy" | "apply" | "pull";

export type Scope = "read" | "profiles:write" | "apply" | "telemetry";


// --- constants ----------------------------------------------------------

/** Reasoning-effort modes, least effort first. */
export const EFFORT_ORDER = ["non-reasoning", "minimal", "low", "medium", "high", "xhigh", "max"] as const;

export type Effort = (typeof EFFORT_ORDER)[number];


// --- models -------------------------------------------------------------

export interface Axis {
  name: string;
  modality: Modality;
  label: string;
  describes: string;
  fields: AxisField[];
  missing?: "renormalise" | "penalise";
  min_coverage?: number;
  higher_is_better?: boolean;
}


export interface AxisField {
  source: string;
  field: string;
  weight?: number;
  transform?: Transform;
  min_n?: number | null;
  phase?: number;
}


export interface AxisScore {
  axis: string;
  value: number | null;
  coverage: number;
  contribution: number;
}


/** One model on the media ranking. */
export interface BoardRow {
  model_id: string;
  name: string;
  creator: string;
  value: number;
  merged?: string[];
}


/** What a model can do. From inventory and OpenRouter; never from a benchmark. */
export interface Capability {
  tools?: boolean | null;
  reasoning?: boolean | null;
  structured_output?: boolean | null;
  context_window?: number | null;
  max_output?: number | null;
  input_modalities?: string[];
  output_modalities?: string[];
}


export interface Chain {
  profile: string;
  computed_at: string;
  primary: string;
  fallbacks?: string[];
  local?: Record<string, string[]>;
  incumbent?: string | null;
  incumbent_since?: string | null;
}


export interface Decision {
  id: string;
  at: string;
  profile: string;
  kind: DecisionKind;
  actor: string;
  before?: unknown | null;
  after?: unknown | null;
  reason: string;
  detail?: Record<string, unknown>;
}


/** What one engine run produced. */
export interface EngineResult {
  snapshot: string;
  at: string;
  rankings?: Ranking[];
  chains?: Chain[];
  decisions?: Decision[];
  targets?: TargetResult[];
  warnings?: string[];
  dry_run?: boolean;
}


/** One model's own traffic, for the Pulse screen. `GET /v1/health` serves these. `health` is the number the ranking multiplies the score by; everything else is ... */
export interface HealthRow {
  model_id: string;
  local_ids?: string[];
  health: number;
  series?: (number | null)[];
  window?: string;
  events?: number;
  ok_rate?: number | null;
  rate_limited_share?: number | null;
  p50_latency_ms?: number | null;
  p95_latency_ms?: number | null;
  median_tokens_out?: number | null;
}


export interface InventoryConfig {
  name: string;
  kind: string;
  base_url?: string | null;
  token_env?: string | null;
  models?: string[];
  options?: Record<string, unknown>;
}


/** A media ranking, and why the screen looks the way it does. The Field scatter plots quality against cost, so a point needs both. Media models almost never hav... */
export interface Leaderboard {
  modality: Modality;
  metric: string;
  metrics?: string[];
  rows?: BoardRow[];
  scored?: number;
  priced?: number;
  priced_share?: number;
  scatter_ok?: boolean;
  low?: number | null;
  high?: number | null;
  reason?: string | null;
  /** which scoreboards the rows came from; more than one is worth showing */
  sources?: string[];
}

/**
 * A source's name in words.
 *
 * `elo` is Artificial Analysis's own unit for its media arenas, so a board
 * labelled only "ranked by elo" reads as though someone else ranked them.
 */
export const SOURCE_LABEL: Record<string, string> = {
  aa_media: 'Artificial Analysis',
  aa_llm: 'Artificial Analysis',
  aa_media_prices: 'Artificial Analysis',
  arena: 'LMArena',
  openrouter: 'OpenRouter',
  deepinfra: 'DeepInfra',
  fal: 'fal',
  manual: 'a manual drop-in'
};

export function sourceWords(sources: string[] | undefined): string {
  const names = [...new Set((sources ?? []).map((s) => SOURCE_LABEL[s] ?? s))];
  if (names.length === 0) return '';
  if (names.length === 1) return names[0];
  return `${names.slice(0, -1).join(', ')} and ${names.at(-1)}`;
}


/** One model, in one modality, under its canonical id. */
export interface ModelRef {
  id: string;
  modality: Modality;
  name: string;
  creator: string;
  aliases?: string[];
  release_date?: string | null;
  effort?: string | null;
  family?: string | null;
}


/** One measured value. Append-only; nothing is ever overwritten. */
export interface Observation {
  model_id: string;
  modality: Modality;
  source: string;
  field: string;
  value: number;
  unit: Unit;
  n?: number | null;
  ci95?: number | null;
  observed_at: string;
  pulled_at: string;
}


export interface Policy {
  margin?: number;
  max_tenure_days?: number;
  min_confidence?: number;
  chain?: number;
  suspend_below_health?: number;
  auto_apply?: boolean;
  require_telemetry?: boolean;
}


export interface Price {
  model_id: string;
  source: string;
  modality?: Modality | null;
  unit: Unit;
  input?: number | null;
  output?: number | null;
  cached_input?: number | null;
  per_unit?: number | null;
  source_url?: string | null;
  tier?: string | null;
  observed_at: string;
}


export interface Profile {
  name: string;
  modality: Modality;
  purpose: string;
  weights: Record<string, number>;
  require?: Record<string, unknown>;
  shape?: Shape;
  policy?: Policy;
  targets?: string[];
  prefer_effort?: string | null;
}


export interface PullResult {
  source: string;
  ok?: boolean;
  models?: ModelRef[];
  observations?: Observation[];
  prices?: Price[];
  capabilities?: Record<string, Capability>;
  provisional?: string[];
  rate_limit?: RateLimit;
  warnings?: string[];
}


export interface Rank {
  position: number;
  model_id: string;
  reachable: boolean;
  local_ids?: string[];
  score: number;
  confidence: number;
  health: number;
  final: number;
  axes?: AxisScore[];
  cost_per_task?: number | null;
  cost_from?: "shape" | "telemetry" | null;
  dominated_by?: string | null;
  excluded_by?: string | null;
  flip?: string | null;
}


export interface Ranking {
  profile: string;
  modality: Modality;
  computed_at: string;
  snapshot: string;
  ranks?: Rank[];
}


export interface RateLimit {
  limit?: number | null;
  remaining?: number | null;
  reset_at?: string | null;
}


/** A model the user can actually reach, and where. */
export interface Reachable {
  inventory: string;
  local_id: string;
  model_id?: string | null;
  capability?: Capability;
  seen_at: string;
}


/** Per profile; only the keys the modality uses. The YAML spells the token fields `in` and `out` (PLAN section 4); both are accepted, and the JSON name stays `i... */
export interface Shape {
  in_tokens?: number | null;
  out_tokens?: number | null;
  cached?: number | null;
  images?: number | null;
  seconds?: number | null;
  chars?: number | null;
  megapixels?: number | null;
  requests?: number | null;
}


/** One `[sources.<name>]` block of sieve.toml, resolved. */
export interface SourceConfig {
  name: string;
  enabled?: boolean;
  key_env?: string | null;
  modalities?: Modality[];
  dir?: string | null;
  options?: Record<string, unknown>;
}


export interface TargetConfig {
  name: string;
  kind: string;
  dir?: string | null;
  url?: string | null;
  options?: Record<string, unknown>;
}


/** What one target holds *now*, against what the engine would write. The Chains screen used to diff against the last `apply` decision, which only says what Siev... */
export interface TargetDiff {
  target: string;
  kind: string;
  supported?: boolean;
  current?: Record<string, string[]>;
  planned?: Record<string, string[]>;
  error?: string | null;
}


export interface TargetResult {
  target: string;
  written?: string[];
  dry_run?: boolean;
  detail?: Record<string, unknown>;
  error?: string | null;
}


export interface TelemetryEvent {
  model: string;
  profile?: string | null;
  ok: boolean;
  status?: number | null;
  latency_ms?: number | null;
  tokens_in?: number | null;
  tokens_out?: number | null;
  at: string;
}
