"""`sieve export-types` — render `contracts.py` into `web/src/lib/types.ts`.

CONTRACTS section 1 named `json-schema-to-typescript` for this step. That would
put Node on the path of a Python command and of the Python CI job; emitting the
TypeScript directly from the same pydantic schemas keeps the command
dependency-free and byte-deterministic, which is what CI diffs against. The
contract itself is unchanged: the file is generated, never hand-edited, and CI
fails if it is stale.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, get_args

from sieve.contracts import EXPORTED, DecisionKind, Modality, Scope, Transform, Unit

HEADER = """// Generated by `sieve export-types` from sieve/contracts.py.
// Do not edit: run `sieve export-types` and commit the result.
"""

ALIASES: dict[str, tuple[str, ...]] = {
    "Modality": get_args(Modality),
    "Unit": get_args(Unit),
    "Transform": get_args(Transform),
    "DecisionKind": get_args(DecisionKind),
    "Scope": get_args(Scope),
}

#: enum value-sets that should render as the named alias rather than inline.
_BY_VALUES = {frozenset(values): name for name, values in ALIASES.items()}


def _union(parts: list[str]) -> str:
    seen: list[str] = []
    for part in parts:
        if part not in seen:
            seen.append(part)
    return " | ".join(seen) if seen else "unknown"


def ts_type(schema: dict[str, Any]) -> str:
    """One JSON-schema node as a TypeScript type."""
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]

    for key in ("anyOf", "oneOf"):
        if key in schema:
            return _union([ts_type(part) for part in schema[key]])

    if "const" in schema:
        return _literal(schema["const"])

    if "enum" in schema:
        values = schema["enum"]
        named = _BY_VALUES.get(frozenset(v for v in values if isinstance(v, str)))
        if named and len(values) == len(ALIASES[named]):
            return named
        return _union([_literal(v) for v in values])

    kind = schema.get("type")
    if isinstance(kind, list):
        return _union([ts_type({**schema, "type": k}) for k in kind])

    if kind == "array":
        items = schema.get("items")
        inner = ts_type(items) if isinstance(items, dict) else "unknown"
        return f"{inner}[]"

    if kind == "object":
        extra = schema.get("additionalProperties")
        if isinstance(extra, dict):
            return f"Record<string, {ts_type(extra)}>"
        if extra is False and "properties" in schema:
            return _inline_object(schema)
        return "Record<string, unknown>"

    if kind == "string":
        return "string"
    if kind in ("number", "integer"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    return "unknown"


def _literal(value: Any) -> str:
    if isinstance(value, str):
        return f'"{value}"'
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    return str(value)


def _inline_object(schema: dict[str, Any]) -> str:
    required = set(schema.get("required", []))
    fields = [
        f"{name}{'' if name in required else '?'}: {ts_type(body)}"
        for name, body in schema.get("properties", {}).items()
    ]
    return "{ " + "; ".join(fields) + " }"


def _describe(schema: dict[str, Any]) -> str | None:
    text = schema.get("description")
    if not text:
        return None
    first = " ".join(str(text).split())
    return first if len(first) <= 160 else first[:157] + "..."


def interface(name: str, schema: dict[str, Any]) -> str:
    """One named model as a TypeScript interface."""
    if "enum" in schema and "properties" not in schema:
        return f"export type {name} = {ts_type(schema)};\n"

    required = set(schema.get("required", []))
    lines: list[str] = []
    doc = _describe(schema)
    if doc:
        lines.append(f"/** {doc} */")
    lines.append(f"export interface {name} {{")
    for prop, body in schema.get("properties", {}).items():
        note = _describe(body)
        if note:
            lines.append(f"  /** {note} */")
        optional = "" if prop in required else "?"
        lines.append(f"  {prop}{optional}: {ts_type(body)};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def collect() -> dict[str, dict[str, Any]]:
    """Every exported model and everything they reference, by name.

    Serialization mode: types.ts describes what the API *returns*, so
    `Shape.in_tokens` is the field name the web sees, not the `in` input alias.
    """
    defs: dict[str, dict[str, Any]] = {}
    for model in EXPORTED:
        schema = model.model_json_schema(ref_template="{model}", mode="serialization")
        for name, body in schema.pop("$defs", {}).items():
            defs.setdefault(name, body)
        defs[schema.get("title", model.__name__)] = schema
    return defs


def render() -> str:
    parts: list[str] = [HEADER]

    parts.append("// --- unions -------------------------------------------------------------\n")
    for name, values in ALIASES.items():
        parts.append(f"export type {name} = {_union([_literal(v) for v in values])};\n")

    parts.append("\n// --- models -------------------------------------------------------------\n")
    for name, schema in sorted(collect().items()):
        if name in ALIASES:
            continue
        parts.append(interface(name, schema))
        parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def write_types(path: str | Path = "web/src/lib/types.ts") -> bool:
    """Write the file if it differs. Returns True when it changed."""
    out = Path(path)
    text = render()
    if out.exists() and out.read_text(encoding="utf-8") == text:
        return False
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8", newline="\n")
    return True
